---
#   __       _ _ ____  _                    ___            _        
#  / _| __ _(_) |___ \| |__   __ _ _ __    / / |_ __ _ ___| | _____ 
# | |_ / _` | | | __) | '_ \ / _` | '_ \  / /| __/ _` / __| |/ / __|
# |  _| (_| | | |/ __/| |_) | (_| | | | |/ / | || (_| \__ \   <\__ \
# |_|  \__,_|_|_|_____|_.__/ \__,_|_| |_/_/   \__\__,_|___/_|\_\___/
#                                                                   
# install-pkg
- block:
    - name: install-pkg | RedHat | fail2ban should be installed
      yum:
        name:  "fail2ban"
        state: "present"
  when: ansible_os_family == "RedHat"

- block:
    - name: install-pkg | Debian | fail2ban should be installed
      apt:
        name:  "fail2ban"
        state: "present"
  when: ansible_os_family == "Debian"

