---
#   __       _ _ ____  _                    ___            _        
#  / _| __ _(_) |___ \| |__   __ _ _ __    / / |_ __ _ ___| | _____ 
# | |_ / _` | | | __) | '_ \ / _` | '_ \  / /| __/ _` / __| |/ / __|
# |  _| (_| | | |/ __/| |_) | (_| | | | |/ / | || (_| \__ \   <\__ \
# |_|  \__,_|_|_|_____|_.__/ \__,_|_| |_/_/   \__\__,_|___/_|\_\___/
# make-config
- name: make-config | Deploy fail2ban.conf into /etc/fail2ban
  notify: Restart fail2ban
  template:
    src:   "etc/fail2ban/{{ item }}.j2"
    dest:  "{{ fail2ban.configroot }}/{{ item }}"
    owner: "root"
    group: "root"
    mode:  "0644"
  loop:
    - "fail2ban.conf"
    - "jail.local"

- name: make-config | Deploy fail2ban.conf into /etc/logrotate.d
  template:
    src:   "etc/logrotate.d/fail2ban.j2"
    dest:  "/etc/logrotate.d/fail2ban"
    owner: "root"
    group: "root"
    mode:  "0644"

